# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
